import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage();
page.on('response', r => { if (r.status() >= 400) console.log('HTTP', r.status(), r.url()); });
await page.goto('http://localhost:4173/login');
await page.getByLabel(/email/i).fill('admin@trak.id');
await page.getByLabel(/password/i).fill('adminpassword123');
await page.getByRole('button', { name: /login/i }).click();
await page.waitForTimeout(6000);
console.log('URL:', page.url());
console.log('TITLE:', await page.title());
const h1 = await page.locator('h1').first().textContent().catch(() => '(no h1)');
console.log('H1:', h1);
await browser.close();
